services:
  - type: web
    name: paystack-payment-processor
    env: docker
    buildCommand: docker build -t paystack-payment-processor .
    startCommand: docker run -p 8080:8080 paystack-payment-processor
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-ctdvp65ds78s739gc8rg-a/paystack_db
      - key: SPRING_DATASOURCE_USERNAME
        value: paystack_db_user
      - key: SPRING_DATASOURCE_PASSWORD
        value: alI891ZMswK1zFcLDUeVHbqa7F8HimX6
      - key: PAYSTACK_API_KEY
        value: ${PAYSTACK_API_KEY}

  - type: postgres
    name: paystack-postgres
    ipAllowList: []
    plan: free
    region: oregon
    version: "16"
